Force mypy to analyze censusdis package
Fix a CI error in mypy:

uv run mypy .
gen_data_helpers.py:2: error: Skipping analyzing "censusdis": module is installed, but missing library stubs or py.typed marker  [import-untyped]
gen_data_helpers.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 5 source files)
make: *** [check] Error 1

Following that link option 4 is:

Force mypy to analyze the library as best as it can (as if the library provided a py.typed file), despite it likely missing any type annotations. In general, the quality of type checking will be poor and mypy may have issues when analyzing code not designed to be type checked.

You can do this via setting the --follow-untyped-imports command line flag or follow_untyped_imports config file option to True. This option can be specified on a per-module basis as well:

pyproject.toml
[[tool.mypy.overrides]]
module = ["untyped_package.*"]
follow_untyped_imports = true

This seems like the best option because I belive that censusdis uses type hints, but does not have a py.typed file. This passes CI.